### ISSUE TITLE
Mobile menu scroll behaviour is unclear

### ISSUE THREAD

**Issue by aeneasr** [ory/web#222]
**Describe the bug**

There are currently a few things confusing in the mobile navigation:

1. The navigation disappears after scrolling past a certain threshold: 

https://user-images.githubusercontent.com/3372410/120776167-372b2100-c524-11eb-950b-1d5bcfa1f43b.mp4

2. It is not clear where I am in the navigation because I do not have a scroll indicator on the left - this leads to a bit wonky mobile menu experience. I think the threshold is also acting a bit strange although I like the idea of being able to "swipe away" the navigation and not having to press the burger at the top.

https://user-images.githubusercontent.com/3372410/120778128-4a3ef080-c526-11eb-8b69-b26ff13b0fad.mp4

https://user-images.githubusercontent.com/3372410/120778148-50cd6800-c526-11eb-86a6-2437dddd5916.mp4

**Expected behavior**

I think https://www.apple.com/ has a nice mobile menu experience

https://user-images.githubusercontent.com/3372410/120776544-a86ad400-c524-11eb-9048-a1246c3b299f.mov

Except for the secondary scroll bar which looks a bit terrible :D

It would also be nice to have an animation for the menu icon when it opens / is open / closes / is closed

**Comment by Benehiko** [comment]
I agree with the fact the it isn't clear where you are in the dropdown (since it has no scrollbar). 

It's also difficult to have a "slide-away" effect with a scrollable mobile dropdown. I made it "slide-away" since i thought it would be good to build on, maybe we can make it a bit more stylish by moving the entire dropdown upwards as you "swipe up" but have it a bit more sticky, so that you can't just accidentally get rid of it, but convenient to be able to get rid of it without touching the hamburger menu - as well as not being able to scroll the parent.

I also think the hamburger icon should change based on what the current view looks like. I think I will need to play around with some css to see what cool effects we can implement - ofc I will need @jfcurran to supervise with those amazing design :eyes:

I will look into this as soon as I have squashed the other bugs :p

**Comment by aeneasr** [comment]
Agreed :) I think it would make sense to give the mobile nav another week of designing and implementation to nail it, once @jfcurran is back from vacation!
